### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by yfarjoun** [constant-flow/arc-breaker#2]
Hi, 
Thanks for this website,

I was wondering if there's an API or if the code is available for download, I'd like to use arc-breaker as a post-processing tool since the gcodetool plugin creates gcode with arcs and my printer (ender5) doesn't understand them...

many thanks,

Yossi.

**Comment by constant-flow** [comment]
I mean you will find the js code [here and following lines](https://github.com/constant-flow/arc-breaker/blob/e76956f9f6c908bf70aa935bb32c19343750579d/index.html#L158)

Feel free to adapt it to your needs :)

**Comment by yfarjoun** [comment]
Thanks! it didn't cross my mind that the code is all embedded in the html!

**Comment by constant-flow** [comment]
No worries. It's not the cleanest I know, but for a small tool like this, it's alright 😉

Maybe also check if you can activate the G2/3 commands in your firmware. IIRC Marlin has a simple bool flag to activate it, dunno if that's an option, just want to let you know
